FROM python:3.8


ENV PATH /usr/local/bin:$PATH
ENV LANG en_US.UTF-8
ENV PYTHONIOENCODING utf-8
ENV PYTHONPATH /work
ENV NOSE_NOCAPTURE 1


RUN mkdir /work
COPY . /work
RUN pip install -r /work/requirements.txt
RUN pip install uvicorn

WORKDIR /work
EXPOSE 8000

CMD ["bash"]
