# echo 112.124.219.217 rsa.xiaowhite.com >> /etc/hosts
version: '2'
services:
    api:
        build:
          context: ./
          dockerfile: Dockerfile.deploy
        tty: true
        environment:
            PYTHONIOENCODING: utf-8
            PYTHONPATH: /work
            DEPLOY: DEVDOCKER
            NOSE_NOCAPTURE: 1
            SIBBAY_MONGODB_USER_HOST: mongodb://mongodb:27017/user

            ICPDAO_GITHUB_APP_CLIENT_ID: xxx
            ICPDAO_GITHUB_APP_CLIENT_SECRET: xxx
            ICPDAO_JWT_RSA_PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAqJhaGu3Wcc98DPauM9+OYeNefteb2BK7BGjWfAppDMmWsxib\niUHx9oR5fP87gWzvFZTlufPU2cxcX6M5y/Lacz9Pz8NL65ViesltTCbNZe2cpQY+\nvaelK2VeaKnGm/kQBT8dBDaVvtSxIFaJe7q240ur0g8S/41mAq5boLdkkJ/5Flhq\npc+1rL0YtlFBs7ptbyyoWPVXcuxLMJE1tTzQohF/UFiSK1qnZ+8zlXWSB2yGy8M5\ngzO3TNtTR5jVFOR9lKsbbNMk2JUdKbRKpHdc2ZkTvi+LjYpRm1Bk4O8ZOjQFBtX0\nN6piGzypb6RbQ5wpQepgbjUGmcyugGLvcn21xwIDAQABAoIBACzWyDAdTUlbm2x/\nNvmI3X9fT0SA52viH2ce0tyOkD3cZ34eb09kAIxF02HRJ+xWIogk36xDEzsRxQeS\ni86YOk0oa3ugP1LamiR56d20/C+9sEmbjZg3PBB8l01SygW1ifM7Q+ZY9h6YxrsJ\nCOulTvrIp1vosm7RFm5kHO5zmAV2d/B4fIEMnvnCaL6XTr8cvWFBu9lZVN2V/CDn\nAFR+rcG4Kkl6SpYlXnnO6paxLysK5mUSBMRedQKQJ7Td+DD+EhfA/O8zqtrWBZOt\n9bn6SNZYkCCdkEQ7IzrOBHV6yDUyQ/eWC4FI58qyafsQ6EPeDaogF+38uXLK+YFl\nAHRVAVECgYEA0RvMgtpxcOZMIBs3lWnk+viLjxukruTFbhgUki/+Xch97T9cMqE+\nKkZ18qvXMlj+1kTFoL5MMe6wTTdKtqlNGw+2hKB7bCLrX7DPUqAbg9DoBDORBiuP\nmo65CTwUxCkEXmtCzGVKxlKyeQLshEFKPsBWH8HQAi77KCvRlF+XF3MCgYEAzmbQ\nr8EhHDuJo28gLK3GGziD00DSm9KVDVhcMOh059BanPCx0cVj1KZfmopUpTy33mky\n2vlR9FSLogcspUPfe9BBkePN3ZFBRyBOquFQjlMxzYT0Vzz53v/iEYoD/Xjmqsf1\nsQLdbwWx3UXQJHzs0L3ykuRQdpqEQ9mgof52y10CgYAeRskgtSIxt5aUG3y7zH5T\n/EKwsM7yZ7tSSnhIBlztFUduX3so9YG7u0H+pfTdnFchjQmUUZlUrXunYncV5YN9\nhJPnthjIunGcBEywaPAy8L93REQeQZZkSX/vH1zeXhX82cjtMUlXV8fxj4PRTmbC\nmTSfGn/UoRrKYTXSJtkIkwKBgBi50mgrn7bNHxj4GAeiLahXJdup2VEXcgmuOyUU\nw+R9Xk2MvBCgL+xqnetahPdihbhcK951na7CbhPT/jIyJlSjxycd/ix72TEXGrV3\n1nmmV8ICGm9U+64OQ1vMh9vWnvN4juNMr5A8Q2l5koy8dnYvOx8DwOvkaNHkAU1G\nuZ51AoGAaTHP2N6mj6OCIdYPi4NjRhLRXyu3umw9fGVGWlkr8b88bXODbyK+6Snp\nBMKhuD07iKxFEQn2IZ4Ifc0yWiVYoTgo1oDwFPnjSqwbObBTTMM10LZyDc3RBQOb\n3ZLF0QqhZNYl33Lz5JS6JxXo+ZIn4GrfEG8+NXMAjhkd4j0xNXs=\n-----END RSA PRIVATE KEY-----
            API_GATEWAY_BASE_PATH: dev/users
            AWS_AUTHORIZER_ARN: xxx
            ICPDAO_MONGODB_ICPDAO_HOST: mongodb://mongodb:27017/icpdao
        ports:
            - "5000:5000"
        links:
            - mongodb
        volumes:
            - "./:/work"
    mongodb:
        image: mongo:4.4
