import os
import redis
from dotenv import load_dotenv

load_dotenv()

ICPDAO_GITHUB_APP_CLIENT_ID = os.environ['ICPDAO_GITHUB_APP_CLIENT_ID']
ICPDAO_GITHUB_APP_CLIENT_SECRET = os.environ['ICPDAO_GITHUB_APP_CLIENT_SECRET']
ICPDAO_JWT_RSA_PRIVATE_KEY = os.environ['ICPDAO_JWT_RSA_PRIVATE_KEY'].replace('\\n', '\n')
API_GATEWAY_BASE_PATH = os.environ['API_GATEWAY_BASE_PATH']
AWS_AUTHORIZER_ARN = os.environ['AWS_AUTHORIZER_ARN']
ICPDAO_AWS_UPLOAD_S3_ROLE_ARN = os.environ['ICPDAO_AWS_UPLOAD_S3_ROLE_ARN']
ICPDAO_AWS_UPLOAD_S3_BUCKET = os.environ['ICPDAO_AWS_UPLOAD_S3_BUCKET']
ICPDAO_AWS_UPLOAD_S3_REGION = os.environ['ICPDAO_AWS_UPLOAD_S3_REGION']
ICPDAO_AWS_UPLOAD_S3_BUCKET_HOST = os.environ['ICPDAO_AWS_UPLOAD_S3_BUCKET_HOST']
ICPDAO_MONGODB_ICPDAO_HOST = os.environ['ICPDAO_MONGODB_ICPDAO_HOST']
ICPDAO_REDIS_LOCK_DB_URL = os.environ['ICPDAO_REDIS_LOCK_DB_URL']

ICPDAO_REDIS_LOCK_DB_CONN = redis.Redis.from_url(ICPDAO_REDIS_LOCK_DB_URL)
ICPDAO_MINT_TOKEN_ETH_CHAIN_ID = os.environ['ICPDAO_MINT_TOKEN_ETH_CHAIN_ID']
